"""Storm-definition sensitivity test at the example sites -> sensitivity.md (next to this script).

Runs step 10's own storm code (step10_reduce_snowfall.loads) on the site series from extract_site_snowfall.py for
every combination of wet-hour threshold (WETS) and longest dry gap (GAPS), over the AZCOT months (Oct-Mar, 1991-2020),
and reports the record storm total, how long that storm lasted, the 99th-percentile storm duration and the number of
storms per season reaching the rigid-shelter load (20 lb/ft2). Fixed-window loads (24/48/72/120 h) are listed for
comparison; they need no storm definition.

Usage: python storm_sensitivity.py   (login node is fine: ~1 min)
"""
import sys
from pathlib import Path

import numpy as np
import xarray as xr

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
import step10_reduce_snowfall as s10  # noqa: E402
from config import OUT_ROOT, SWE_M_TO_SL  # noqa: E402

WETS = (0.05, 0.1, 0.2)  # mm water equivalent per hour
GAPS = (6, 12, 24)       # hours
CHOSEN = (s10.WET_MM_H, s10.GAP_H)
LIMIT = 20.0             # lb/ft2, rigid shelters


def main():
    ds = xr.open_dataset(OUT_ROOT / "storm_definition" / "sf_sites.nc")
    t = ds.time.values
    mon = t.astype("datetime64[M]").astype(int) % 12 + 1
    yr = t.astype("datetime64[Y]").astype(int) + 1970
    keep = np.isin(mon, [10, 11, 12, 1, 2, 3]) & (yr >= 1991) & (yr <= 2020)
    windows, storms = [], []
    saved = (s10.WET_MM_H, s10.GAP_H)
    for site in ds.data_vars:
        sf = np.maximum(ds[site].values.astype(np.float64), 0)[:, None]
        roll = {h: (np.convolve(sf[:, 0], np.ones(h), "full")[:len(sf)] * SWE_M_TO_SL)[keep].max()
                for h in (24, 48, 72, 120)}
        season = sf[keep, 0].sum() * SWE_M_TO_SL / 30
        windows.append(f"| {site} | {season:.0f} | {roll[24]:.1f} | {roll[48]:.1f} | {roll[72]:.1f} | {roll[120]:.1f} |")
        for wet in WETS:
            for gap in GAPS:
                s10.WET_MM_H, s10.GAP_H = wet, gap
                _, _, total, dur = s10.loads(sf, len(sf) - 1)
                e = (total[:, 0] > 0) & keep
                tot, d = total[e, 0] * SWE_M_TO_SL, dur[e, 0]
                k = int(tot.argmax())
                mark = "**yes**" if (wet, gap) == CHOSEN else ""
                storms.append(f"| {site} | {wet:g} | {gap} | {tot[k]:.1f} | {d[k]} h ({d[k] / 24:.1f} d) | "
                              f"{np.percentile(d, 99):.0f} h | {(tot >= LIMIT).sum() / 30:.2f} | {mark} |")
    s10.WET_MM_H, s10.GAP_H = saved
    md = ["# Storm-definition sensitivity (generated by storm_sensitivity.py; do not edit)", "",
          "ERA5 hourly snowfall at the example sites, Oct-Mar 1991-2020. Loads in lb/ft2 "
          "(water equivalent x 204.7 lb/ft2 per m).", "",
          "## Fixed windows (no storm definition needed)", "",
          "| site | mean snowfall per season | record 24 h | record 48 h | record 72 h | record 120 h |",
          "|---|---:|---:|---:|---:|---:|", *windows, "",
          "## Storm totals by definition", "",
          "wet = smallest hourly snowfall that counts as snowing (mm w.e.); gap = longest dry spell (h) inside one storm.", "",
          "| site | wet | gap | record storm total | that storm lasted | 99th-pct duration | storms/season >= 20 | used |",
          "|---|---:|---:|---:|---:|---:|---:|---|", *storms, ""]
    (HERE / "sensitivity.md").write_text("\n".join(md))
    print("wrote", HERE / "sensitivity.md")


if __name__ == "__main__":
    main()
